name: Update readme

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # 1. Genera il profilo 3D
      - name: Generate 3D contribution profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: ./3d-profile-settings.json

      # 2. Genera le statistiche contributi
      # Nota: Questa azione scarica automaticamente il binario corretto
      - name: Update contribute stats
        uses: elax46/github-contrib-stats@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
          filename: contribution.md

      # 3. Salva tutto nel repository
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update readme daily"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com